# Generated by Django 5.0 on 2025-05-04 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection', to='prompt_app.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='static/prompt_app/audio/')),
                ('transcript', models.FileField(upload_to='static/prompt_app/transcripts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='prompt_app.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False)),
                ('identity', models.CharField(max_length=280)),
                ('prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlights', to='prompt_app.prompt')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight', to='prompt_app.response')),
            ],
        ),
    ]
