# Generated by Django 5.0 on 2025-05-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
