# Generated by Django 5.0 on 2025-05-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_app', '0002_response_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='identity',
        ),
        migrations.AddField(
            model_name='response',
            name='identity',
            field=models.CharField(default='Anonymous', max_length=280),
        ),
    ]
