# Generated by Django 5.0 on 2025-05-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_app', '0003_remove_highlight_identity_response_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='audio',
            field=models.FileField(upload_to='prompt_app/audio/'),
        ),
        migrations.AlterField(
            model_name='response',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Highlight',
        ),
    ]
