# Generated by Django 5.0 on 2025-05-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_app', '0004_response_public_alter_response_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
